name: 'hexo-deploy-with-CNAME-enabled'
description: 'This GitHub action will handle the building and deploying process of hexo project with CNAME is enabled'
author: 'Forest10'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-commit'
  color: 'orange'
